apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ctf
  namespace: ctf
  labels:
    team: ctf
spec:
  image: {{ image }}
  port: 8000
  ingresses:
    - https://ctf.intern.dev.nav.no
  liveness:
    path: /
  readiness:
    path: /
  replicas:
    min: 1
    max: 1
  redis:
    - instance: ctf
      access: readwrite
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - envVarPrefix: DATABASE
            name: ctf